apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: c1
        image: vaibhavkalel/wimage2  # Replace with your actual Docker image and tag
        ports:
        - containerPort: 8000
