apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weather-app
  name: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather-app
    spec:
      containers:
      - image: vaibhavkalel/weather-image3:latest
        name: c1
        resources: {}
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: weather-app
  name: weather-app
spec:
  ports:
  - name: app-ports
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32411
  selector:
    app: weather-app
  type: NodePort

